version: '3.8'

services:
  db:
    image: postgres:16
    container_name: javal-postgres
    restart: always
    environment:
      POSTGRES_DB: javal_db
      POSTGRES_USER: javal_user
      POSTGRES_PASSWORD: javal_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: